//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireFestDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentInfo()
        {
            this.AssessmentQuestions = new HashSet<AssessmentQuestion>();
            this.CandidateAssessments = new HashSet<CandidateAssessment>();
        }
    
        public long AssessmentId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Topics { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAssessment> CandidateAssessments { get; set; }
    }
}
