//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireFestDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentQuestion()
        {
            this.CandidateAnswers = new HashSet<CandidateAnswer>();
            this.QuestionOptions = new HashSet<QuestionOption>();
        }
    
        public long QuestionId { get; set; }
        public Nullable<long> assessmentInfoId { get; set; }
        public string Question { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual AssessmentInfo AssessmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
    }
}
