//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireFestDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAssessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateAssessment()
        {
            this.CandidateAnswers = new HashSet<CandidateAnswer>();
        }
    
        public long id { get; set; }
        public Nullable<long> candidateId { get; set; }
        public Nullable<long> assessmentId { get; set; }
        public Nullable<int> Score { get; set; }
        public string Status { get; set; }
    
        public virtual AssessmentInfo AssessmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
