//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireFestDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAnswer
    {
        public long id { get; set; }
        public Nullable<long> candidateAssessmentId { get; set; }
        public Nullable<long> assessmentQuestionId { get; set; }
        public Nullable<long> questionOptionId { get; set; }
    
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
        public virtual CandidateAssessment CandidateAssessment { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
    }
}
