//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireFestDAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HireFestEntities : DbContext
    {
        public HireFestEntities()
            : base("name=HireFestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentInfo> AssessmentInfoes { get; set; }
        public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }
        public virtual DbSet<CandidateAnswer> CandidateAnswers { get; set; }
        public virtual DbSet<CandidateAssessment> CandidateAssessments { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
    }
}
